# Generated by Django 5.0.6 on 2024-07-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='students', to='App.project'),
        ),
    ]
